### ISSUE TITLE
Frase mais específica 

### ISSUE THREAD

**Issue by canogg** [vinicius-lavor/swift-challenge#1]
https://github.com/vinicius-lavor/swift-challenge/blob/f50671f867b0b7eed4f45385fc34dcf03471b4c6/SwiftChallenge/main.swift#L213

Amei o programa, super usaria no meu dia a dia! Acredito que para o melhor entendimento do usuário a frase “Para você” no inicio do programa poderia ser um pouquinho mais específica, como por exemplo: Chá recomendado para ajudar no seu dia hoje

**Comment by vinicius-lavor** [comment]
Obrigado! A frase foi corrigida.
