### ISSUE TITLE
Trocar class por struct

### ISSUE THREAD

**Issue by mtsrodrigues** [vinicius-lavor/swift-challenge#13]
https://github.com/vinicius-lavor/swift-challenge/blob/56880b9feeb9a7bf750be6ca34bbcb6b817cff79/SwiftChallenge/main.swift#L20-L28

Essa class poderia ser trocada por uma struct que tem a vantagem de gerar um inicializador padrão a partir da listas de propriedade, por exemplo:
```swift
struct Point {
    let x: Int
    let y: Int
}

let point = Point(x: 10, y: 10)
```

[Memberwise Initializers for Structure Types](https://docs.swift.org/swift-book/LanguageGuide/ClassesAndStructures.html#ID87)

**Comment by vinicius-lavor** [comment]
Muito obrigado, alteração feita!
